import Seasons from './Seasons';
import Weather from './Weather';
import Location from './Locations';

const Fish = [
    {
        name: "Largemouth Bass",
        difficulty: 50,
        motion: "mixed",
        minSize: 11,
        maxSize: 30,
        minTime: 600,
        maxTime: 1900,
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.4,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        advanced: true,
        location: Location.MOUNTAIN_LAKE,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        name: "Carp",
        difficulty: 15,
        motion: "mixed",
        minSize: 15,
        maxSize: 50,
        minTime: 600,
        maxTime: 2600,
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.MOUNTAIN_LAKE | Location.POND_SECRET | Location.SEWERS,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        name: "Green Algae",
        difficulty: 5,
        motion: "floater",
        minSize: 5,
        maxSize: 30,
        minTime: 600,
        maxTime: 2600,
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 0,
        spawnMultiplier: 0.3,
        depthMultiplier: 0,
        requiredLevel: 0,
        advanced: false,
        location: Location.BASE_FRESHWATER,
        baseValue: 15,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        name: "Bullhead",
        difficulty: 46,
        motion: "smooth",
        minSize: 12,
        maxSize: 30,
        minTime: 600,
        maxTime: 2600,
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.35,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        advanced: false,
        location: Location.MOUNTAIN_LAKE,
        baseValue: 75,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        name: "Chub",
        difficulty: 35,
        motion: "dart",
        minSize: 12,
        maxSize: 24,
        minTime: 600,
        maxTime: 2600,
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.MOUNTAIN_LAKE | Location.RIVER_FOREST,
        baseValue: 50,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        name: "Sunfish",
        difficulty: 30,
        motion: "mixed",
        minSize: 5,
        maxSize: 15,
        minTime: 600,
        maxTime: 1900,
        seasons: Seasons.SPRING | Seasons.SUMMER,
        weather: Weather.SUNNY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.RIVER_TOWN | Location.RIVER_FOREST,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        name: "Catfish",
        difficulty: 75,
        motion: "mixed",
        minSize: 12,
        maxSize: 72,
        minTime: 600,
        maxTime: 2400,
        seasons: Seasons.SPRING | Seasons.FALL | Seasons.WINTER,
        weather: Weather.RAINY,
        bestDepth: 4,
        spawnMultiplier: 0.4,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: true,
        location: Location.RIVER_TOWN | Location.RIVER_FOREST | Location.POND_SECRET | Location.SWAMP,
        baseValue: 200,
        baseEnergy: 50,
        baseHealing: 22
    },
    {
        name: "Bream",
        difficulty: 35,
        motion: "smooth",
        minSize: 12,
        maxSize: 30,
        minTime: 1800,
        maxTime: 2600,
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.RIVER_TOWN | Location.RIVER_FOREST,
        baseValue: 45,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        name: "Shad",
        difficulty: 45,
        motion: "smooth",
        minSize: 20,
        maxSize: 48,
        minTime: 900,
        maxTime: 2600,
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL,
        weather: Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.35,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        advanced: false,
        location: Location.MOUNTAIN_LAKE | Location.RIVER_FOREST,
        baseValue: 60,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        name: "Anchovy",
        difficulty: 30,
        motion: "dart",
        minSize: 1,
        maxSize: 16,
        minTime: 600,
        maxTime: 2600,
        seasons: Seasons.SPRING | Seasons.FALL,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.25,
        depthMultiplier: 0.3,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        name: "Sardine",
        difficulty: 30,
        motion: "dart",
        minSize: 1,
        maxSize: 12,
        minTime: 600,
        maxTime: 1900,
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.65,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 40,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        name: "Herring",
        difficulty: 25,
        motion: "dart",
        minSize: 8,
        maxSize: 20,
        minTime: 600,
        maxTime: 2600,
        seasons: Seasons.SPRING | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        name: "Eel",
        difficulty: 70,
        motion: "smooth",
        minSize: 12,
        maxSize: 80,
        minTime: 1600,
        maxTime: 2600,
        seasons: Seasons.SPRING | Seasons.FALL,
        weather: Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.55,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: true,
        location: Location.OCEAN_STARDEW,
        baseValue: 85,
        baseEnergy: 30,
        baseHealing: 13
    },
    {
        name: "Seaweed",
        difficulty: 5,
        motion: "floater",
        minSize: 5,
        maxSize: 30,
        minTime: 600,
        maxTime: 2600,
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 0,
        spawnMultiplier: 0.30,
        depthMultiplier: 0.0,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 20,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        name: "Halibut (AM)",
        difficulty: 50,
        motion: "sinker",
        minSize: 10,
        maxSize: 33,
        minTime: 600,
        maxTime: 1100,
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.4,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        advanced: true,
        location: Location.OCEAN_STARDEW,
        baseValue: 80,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        name: "Halibut (PM)",
        difficulty: 50,
        motion: "sinker",
        minSize: 10,
        maxSize: 33,
        minTime: 1900,
        maxTime: 2600,
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.4,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        advanced: true,
        location: Location.OCEAN_STARDEW,
        baseValue: 80,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        name: "Flounder",
        difficulty: 50,
        motion: "sinker",
        minSize: 4,
        maxSize: 16,
        minTime: 600,
        maxTime: 2000,
        seasons: Seasons.SPRING | Seasons.SUMMER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.15,
        depthMultiplier: 0.05,
        requiredLevel: 0,
        advanced: true,
        location: Location.OCEAN_STARDEW,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17
    }
];

export default Fish;