import Seasons from './Seasons';
import Weather from './Weather';
import Location from './Locations';

const Fish = [
    {
        id: 136,
        name: "Largemouth Bass",
        difficulty: 50,
        motion: "mixed",
        minSize: 11,
        maxSize: 30,
        time: [600, 1900],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.4,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        advanced: true,
        location: Location.MOUNTAIN_LAKE,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 142,
        name: "Carp",
        difficulty: 15,
        motion: "mixed",
        minSize: 15,
        maxSize: 50,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.MOUNTAIN_LAKE | Location.POND_SECRET | Location.SEWERS,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 153,
        name: "Green Algae",
        difficulty: 5,
        motion: "floater",
        minSize: 5,
        maxSize: 30,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 0,
        spawnMultiplier: 0.3,
        depthMultiplier: 0,
        requiredLevel: 0,
        advanced: false,
        location: Location.BASE_FRESHWATER,
        baseValue: 15,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 157,
        name: "White Algae",
        difficulty: 5,
        motion: "floater",
        minSize: 5,
        maxSize: 30,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 0,
        spawnMultiplier: 0.3,
        depthMultiplier: 0,
        requiredLevel: 0,
        advanced: false,
        location: Location.MINES_20 | Location.MINES_60 | Location.MINES_100 | Location.SEWERS | Location.SWAMP | Location.BUG_LAIR,
        baseValue: 25,
        baseEnergy: 20,
        baseHealing: 9
    },
    {
        id: 700,
        name: "Bullhead",
        difficulty: 46,
        motion: "smooth",
        minSize: 12,
        maxSize: 30,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.35,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        advanced: false,
        location: Location.MOUNTAIN_LAKE,
        baseValue: 75,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 702,
        name: "Chub",
        difficulty: 35,
        motion: "dart",
        minSize: 12,
        maxSize: 24,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.MOUNTAIN_LAKE | Location.RIVER_FOREST,
        baseValue: 50,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 145,
        name: "Sunfish",
        difficulty: 30,
        motion: "mixed",
        minSize: 5,
        maxSize: 15,
        time: [600, 1900],
        seasons: Seasons.SPRING | Seasons.SUMMER,
        weather: Weather.SUNNY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.RIVER_TOWN | Location.RIVER_FOREST,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 143,
        name: "Catfish",
        difficulty: 75,
        motion: "mixed",
        minSize: 12,
        maxSize: 72,
        time: [600, 2400],
        seasons: Seasons.SPRING | Seasons.FALL | Seasons.WINTER,
        weather: Weather.RAINY,
        bestDepth: 4,
        spawnMultiplier: 0.4,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: true,
        location: Location.RIVER_TOWN | Location.RIVER_FOREST | Location.POND_SECRET | Location.SWAMP,
        baseValue: 200,
        baseEnergy: 50,
        baseHealing: 22
    },
    {
        id: 132,
        name: "Bream",
        difficulty: 35,
        motion: "smooth",
        minSize: 12,
        maxSize: 30,
        time: [1800, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.RIVER_TOWN | Location.RIVER_FOREST,
        baseValue: 45,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 706,
        name: "Shad",
        difficulty: 45,
        motion: "smooth",
        minSize: 20,
        maxSize: 48,
        time: [900, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL,
        weather: Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.35,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        advanced: false,
        location: Location.MOUNTAIN_LAKE | Location.RIVER_FOREST,
        baseValue: 60,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 129,
        name: "Anchovy",
        difficulty: 30,
        motion: "dart",
        minSize: 1,
        maxSize: 16,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.FALL,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.25,
        depthMultiplier: 0.3,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 131,
        name: "Sardine",
        difficulty: 30,
        motion: "dart",
        minSize: 1,
        maxSize: 12,
        time: [600, 1900],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.65,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 40,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 143,
        name: "Herring",
        difficulty: 25,
        motion: "dart",
        minSize: 8,
        maxSize: 20,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 148,
        name: "Eel",
        difficulty: 70,
        motion: "smooth",
        minSize: 12,
        maxSize: 80,
        time: [1600, 2600],
        seasons: Seasons.SPRING | Seasons.FALL,
        weather: Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.55,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        advanced: true,
        location: Location.OCEAN_STARDEW,
        baseValue: 85,
        baseEnergy: 30,
        baseHealing: 13
    },
    {
        id: 152,
        name: "Seaweed",
        difficulty: 5,
        motion: "floater",
        minSize: 5,
        maxSize: 30,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 0,
        spawnMultiplier: 0.30,
        depthMultiplier: 0.0,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 20,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 708,
        name: "Halibut",
        difficulty: 50,
        motion: "sinker",
        minSize: 10,
        maxSize: 33,
        time: [600, 1100, 1900, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.4,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        advanced: true,
        location: Location.OCEAN_STARDEW,
        baseValue: 80,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 267,
        name: "Flounder",
        difficulty: 50,
        motion: "sinker",
        minSize: 4,
        maxSize: 16,
        time: [600, 2000],
        seasons: Seasons.SPRING | Seasons.SUMMER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.15,
        depthMultiplier: 0.05,
        requiredLevel: 0,
        advanced: true,
        location: Location.OCEAN_STARDEW | Location.GINGER_NORTH | Location.GINGER_SOUTH | Location.GINGER_WEST | Location.PIRATE_COVE,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 734,
        name: "Woodskip",
        difficulty: 50,
        motion: "mixed",
        minSize: 11,
        maxSize: 30,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.20,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        advanced: false,
        location: Location.POND_SECRET | Location.FOREST_FARM,
        baseValue: 75,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 130,
        name: "Tuna",
        difficulty: 70,
        motion: "smooth",
        minSize: 12,
        maxSize: 60,
        time: [600, 1900],
        seasons: Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.15,
        depthMultiplier: 0.55,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW | Location.GINGER_NORTH | Location.GINGER_SOUTH | Location.GINGER_WEST | Location.PIRATE_COVE,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 146,
        name: "Red Mullet",
        difficulty: 55,
        motion: "smooth",
        minSize: 8,
        maxSize: 22,
        time: [600, 1900],
        seasons: Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.15,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 75,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 150,
        name: "Red Snapper",
        difficulty: 40,
        motion: "mixed",
        minSize: 8,
        maxSize: 25,
        time: [600, 1900],
        seasons: Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 50,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 151,
        name: "Squid",
        difficulty: 75,
        motion: "sinker",
        minSize: 12,
        maxSize: 48,
        time: [1800, 2600],
        seasons: Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.35,
        depthMultiplier: 0.30,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 80,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 154,
        name: "Sea Cucumber",
        difficulty: 40,
        motion: "sinker",
        minSize: 3,
        maxSize: 20,
        time: [600, 1900],
        seasons: Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.25,
        depthMultiplier: 0.25,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 75,
        baseEnergy: -25,
        baseHealing: 0
    },
    {
        id: 705,
        name: "Albacore",
        difficulty: 60,
        motion: "mixed",
        minSize: 20,
        maxSize: 40,
        time: [600, 1100, 1800, 2600],
        seasons: Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.30,
        depthMultiplier: 0.15,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 75,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 155,
        name: "Super Cucumber",
        difficulty: 80,
        motion: "sinker",
        minSize: 12,
        maxSize: 36,
        time: [1800, 2600],
        seasons: Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 4,
        spawnMultiplier: 0.10,
        depthMultiplier: 0.25,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 250,
        baseEnergy: 125,
        baseHealing: 56
    },
    {
        id: 701,
        name: "Tilapia",
        difficulty: 50,
        motion: "mixed",
        minSize: 11,
        maxSize: 30,
        time: [600, 1400],
        seasons: Seasons.SUMMER | Seasons.FALL,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.20,
        requiredLevel: 0,
        advanced: false,
        location: Location.OCEAN_STARDEW,
        baseValue: 75,
        baseEnergy: 25,
        baseHealing: 11
    }
];

export default Fish;