import Seasons from './Seasons';
import Weather from './Weather';
import Location from './Locations';

const Fish = [
    {
        id: 136,
        name: "Largemouth Bass",
        difficulty: 50,
        motion: "mixed",
        minSize: 11,
        maxSize: 30,
        time: [600, 1900],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.4,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        location: Location.MOUNTAIN_LAKE,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17,

    },
    {
        id: 142,
        name: "Carp",
        difficulty: 15,
        motion: "mixed",
        minSize: 15,
        maxSize: 50,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        location: Location.MOUNTAIN_LAKE | Location.POND_SECRET | Location.SEWERS,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 153,
        name: "Green Algae",
        difficulty: 5,
        motion: "floater",
        minSize: 5,
        maxSize: 30,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 0,
        spawnMultiplier: 0.3,
        depthMultiplier: 0,
        requiredLevel: 0,
        location: Location.BASE_FRESHWATER | Location.SWAMP | Location.SEWERS | Location.BUG_LAIR,
        baseValue: 15,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 157,
        name: "White Algae",
        difficulty: 5,
        motion: "floater",
        minSize: 5,
        maxSize: 30,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 0,
        spawnMultiplier: 0.3,
        depthMultiplier: 0,
        requiredLevel: 0,
        location: Location.MINES_20 | Location.MINES_60 | Location.MINES_100 | Location.SEWERS | Location.SWAMP | Location.BUG_LAIR,
        baseValue: 25,
        baseEnergy: 20,
        baseHealing: 9
    },
    {
        id: 700,
        name: "Bullhead",
        difficulty: 46,
        motion: "smooth",
        minSize: 12,
        maxSize: 30,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.35,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        location: Location.MOUNTAIN_LAKE,
        baseValue: 75,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 702,
        name: "Chub",
        difficulty: 35,
        motion: "dart",
        minSize: 12,
        maxSize: 24,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        location: Location.MOUNTAIN_LAKE | Location.RIVER_FOREST,
        baseValue: 50,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 145,
        name: "Sunfish",
        difficulty: 30,
        motion: "mixed",
        minSize: 5,
        maxSize: 15,
        time: [600, 1900],
        seasons: Seasons.SPRING | Seasons.SUMMER,
        weather: Weather.SUNNY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        location: Location.RIVER_TOWN | Location.RIVER_FOREST,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 143,
        name: "Catfish",
        difficulty: 75,
        motion: "mixed",
        minSize: 12,
        maxSize: 72,
        time: [600, 2400],
        seasons: Seasons.SPRING | Seasons.FALL | Seasons.WINTER,
        weather: Weather.RAINY,
        bestDepth: 4,
        spawnMultiplier: 0.4,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        location: Location.RIVER_TOWN | Location.RIVER_FOREST | Location.POND_SECRET | Location.SWAMP,
        baseValue: 200,
        baseEnergy: 50,
        baseHealing: 22
    },
    {
        id: 132,
        name: "Bream",
        difficulty: 35,
        motion: "smooth",
        minSize: 12,
        maxSize: 30,
        time: [1800, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        location: Location.RIVER_TOWN | Location.RIVER_FOREST,
        baseValue: 45,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 706,
        name: "Shad",
        difficulty: 45,
        motion: "smooth",
        minSize: 20,
        maxSize: 48,
        time: [900, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL,
        weather: Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.35,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        location: Location.MOUNTAIN_LAKE | Location.RIVER_FOREST | Location.RIVER_TOWN,
        baseValue: 60,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 129,
        name: "Anchovy",
        difficulty: 30,
        motion: "dart",
        minSize: 1,
        maxSize: 16,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.FALL,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.25,
        depthMultiplier: 0.3,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 131,
        name: "Sardine",
        difficulty: 30,
        motion: "dart",
        minSize: 1,
        maxSize: 12,
        time: [600, 1900],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.65,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW,
        baseValue: 40,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 143,
        name: "Herring",
        difficulty: 25,
        motion: "dart",
        minSize: 8,
        maxSize: 20,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW,
        baseValue: 30,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 148,
        name: "Eel",
        difficulty: 70,
        motion: "smooth",
        minSize: 12,
        maxSize: 80,
        time: [1600, 2600],
        seasons: Seasons.SPRING | Seasons.FALL,
        weather: Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.55,
        depthMultiplier: 0.1,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW,
        baseValue: 85,
        baseEnergy: 30,
        baseHealing: 13
    },
    {
        id: 152,
        name: "Seaweed",
        difficulty: 5,
        motion: "floater",
        minSize: 5,
        maxSize: 30,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 0,
        spawnMultiplier: 0.30,
        depthMultiplier: 0.0,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW | Location.NIGHT_MARKET,
        baseValue: 20,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 708,
        name: "Halibut",
        difficulty: 50,
        motion: "sinker",
        minSize: 10,
        maxSize: 33,
        time: [600, 1100, 1900, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.4,
        depthMultiplier: 0.2,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW,
        baseValue: 80,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 267,
        name: "Flounder",
        difficulty: 50,
        motion: "sinker",
        minSize: 4,
        maxSize: 16,
        time: [600, 2000],
        seasons: Seasons.SPRING | Seasons.SUMMER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.15,
        depthMultiplier: 0.05,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW | Location.GINGER_SOUTH | Location.GINGER_SEAST | Location.GINGER_W_OCEAN | Location.PIRATE_COVE,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 734,
        name: "Woodskip",
        difficulty: 50,
        motion: "mixed",
        minSize: 11,
        maxSize: 30,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.20,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.POND_SECRET | Location.FOREST_FARM,
        baseValue: 75,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 130,
        name: "Tuna",
        difficulty: 70,
        motion: "smooth",
        minSize: 12,
        maxSize: 60,
        time: [600, 1900],
        seasons: Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.15,
        depthMultiplier: 0.55,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW | Location.GINGER_SOUTH | Location.GINGER_SEAST | Location.GINGER_W_OCEAN | Location.PIRATE_COVE,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 146,
        name: "Red Mullet",
        difficulty: 55,
        motion: "smooth",
        minSize: 8,
        maxSize: 22,
        time: [600, 1900],
        seasons: Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.15,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW,
        baseValue: 75,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 150,
        name: "Red Snapper",
        difficulty: 40,
        motion: "mixed",
        minSize: 8,
        maxSize: 25,
        time: [600, 1900],
        seasons: Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW,
        baseValue: 50,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 151,
        name: "Squid",
        difficulty: 75,
        motion: "sinker",
        minSize: 12,
        maxSize: 48,
        time: [1800, 2600],
        seasons: Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.35,
        depthMultiplier: 0.30,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW,
        baseValue: 80,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 154,
        name: "Sea Cucumber",
        difficulty: 40,
        motion: "sinker",
        minSize: 3,
        maxSize: 20,
        time: [600, 1900],
        seasons: Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.25,
        depthMultiplier: 0.25,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW | Location.NIGHT_MARKET,
        baseValue: 75,
        baseEnergy: -25,
        baseHealing: 0
    },
    {
        id: 705,
        name: "Albacore",
        difficulty: 60,
        motion: "mixed",
        minSize: 20,
        maxSize: 40,
        time: [600, 1100, 1800, 2600],
        seasons: Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.30,
        depthMultiplier: 0.15,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW,
        baseValue: 75,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 155,
        name: "Super Cucumber",
        difficulty: 80,
        motion: "sinker",
        minSize: 12,
        maxSize: 36,
        time: [1800, 2600],
        seasons: Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 4,
        spawnMultiplier: 0.10,
        depthMultiplier: 0.25,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW | Location.NIGHT_MARKET | Location.GINGER_SOUTH | Location.GINGER_W_OCEAN | Location.PIRATE_COVE,
        baseValue: 250,
        baseEnergy: 125,
        baseHealing: 56
    },
    {
        id: 701,
        name: "Tilapia",
        difficulty: 50,
        motion: "mixed",
        minSize: 11,
        maxSize: 30,
        time: [600, 1400],
        seasons: Seasons.SUMMER | Seasons.FALL,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.20,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW | Location.GINGER_W_FRESH | Location.GINGER_NORTH,
        baseValue: 75,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 128,
        name: "Pufferfish",
        difficulty: 80,
        motion: "float",
        minSize: 1,
        maxSize: 36,
        time: [1200, 1600],
        seasons: Seasons.SUMMER,
        weather: Weather.SUNNY,
        bestDepth: 4,
        spawnMultiplier: 0.30,
        depthMultiplier: 0.50,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW | Location.GINGER_SOUTH | Location.GINGER_SEAST | Location.GINGER_W_OCEAN | Location.PIRATE_COVE,
        baseValue: 200,
        baseEnergy: -100,
        baseHealing: 0
    },
    {
        id: 149,
        name: "Octopus",
        difficulty: 95,
        motion: "sinker",
        minSize: 12,
        maxSize: 48,
        time: [600, 1300],
        seasons: Seasons.SUMMER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 5,
        spawnMultiplier: 0.10,
        depthMultiplier: 0.08,
        requiredLevel: 0,
        location: Location.OCEAN_STARDEW | Location.NIGHT_MARKET | Location.GINGER_W_OCEAN,
        baseValue: 150,
        baseEnergy: 0,
        baseHealing: 0
    },
    {
        id: 140,
        name: "Walleye",
        difficulty: 45,
        motion: "smooth",
        minSize: 10,
        maxSize: 40,
        time: [1200, 2600],
        seasons: Seasons.FALL | Seasons.WINTER,
        weather: Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.15,
        requiredLevel: 0,
        location: Location.RIVER_FOREST | Location.RIVER_TOWN | Location.MOUNTAIN_LAKE | Location.POND_FOREST | Location.FOREST_FARM,
        baseValue: 105,
        baseEnergy: 30,
        baseHealing: 13
    },
    {
        id: 141,
        name: "Perch",
        difficulty: 35,
        motion: "dart",
        minSize: 10,
        maxSize: 24,
        time: [600, 2600],
        seasons: Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.RIVER_TOWN | Location.RIVER_FOREST | Location.MOUNTAIN_LAKE | Location.POND_FOREST,
        baseValue: 55,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 144,
        name: "Pike",
        difficulty: 60,
        motion: "dart",
        minSize: 15,
        maxSize: 60,
        time: [600, 2600],
        seasons: Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.15,
        requiredLevel: 0,
        location: Location.RIVER_FOREST | Location.RIVER_TOWN | Location.POND_FOREST,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 707,
        name: "Lingcod",
        difficulty: 85,
        motion: "mixed",
        minSize: 30,
        maxSize: 50,
        time: [600, 2600],
        seasons: Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.30,
        depthMultiplier: 0.05,
        requiredLevel: 0,
        location: Location.RIVER_FOREST | Location.RIVER_TOWN | Location.MOUNTAIN_LAKE,
        baseValue: 120,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 699,
        name: "Tiger Trout",
        difficulty: 60,
        motion: "dart",
        minSize: 10,
        maxSize: 20,
        time: [600, 1900],
        seasons: Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.20,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.RIVER_FOREST | Location.RIVER_TOWN,
        baseValue: 150,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 139,
        name: "Salmon",
        difficulty: 50,
        motion: "mixed",
        minSize: 24,
        maxSize: 65,
        time: [600, 1900],
        seasons: Seasons.FALL,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.20,
        requiredLevel: 0,
        location: Location.RIVER_FOREST | Location.RIVER_TOWN,
        baseValue: 75,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 137,
        name: "Smallmouth Bass",
        difficulty: 28,
        motion: "mixed",
        minSize: 12,
        maxSize: 24,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.FALL,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.45,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.RIVER_TOWN | Location.POND_FOREST,
        baseValue: 50,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 138,
        name: "Rainbow Trout",
        difficulty: 45,
        motion: "mixed",
        minSize: 10,
        maxSize: 25,
        time: [600, 1900],
        seasons: Seasons.SUMMER,
        weather: Weather.SUNNY,
        bestDepth: 2,
        spawnMultiplier: 0.35,
        depthMultiplier: 0.30,
        requiredLevel: 0,
        location: Location.RIVER_TOWN | Location.RIVER_FOREST | Location.MOUNTAIN_LAKE,
        baseValue: 65,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 704,
        name: "Dorado",
        difficulty: 78,
        motion: "mixed",
        minSize: 24,
        maxSize: 32,
        time: [600, 1900],
        seasons: Seasons.SUMMER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.15,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.RIVER_FOREST,
        baseValue: 100,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 164,
        name: "Sandfish",
        difficulty: 65,
        motion: "mixed",
        minSize: 8,
        maxSize: 24,
        time: [600, 2000],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.65,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.DESERT,
        baseValue: 75,
        baseEnergy: 13,
        baseHealing: 5
    },
    {
        id: 165,
        name: "Scorpion Carp",
        difficulty: 90,
        motion: "dart",
        minSize: 12,
        maxSize: 32,
        time: [600, 2000],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.15,
        depthMultiplier: 0.10,
        requiredLevel: 4,
        location: Location.DESERT,
        baseValue: 150,
        baseEnergy: -125,
        baseHealing: 0
    },
    {
        id: 698,
        name: "Sturgeon",
        difficulty: 78,
        motion: "mixed",
        minSize: 12,
        maxSize: 60,
        time: [600, 1900],
        seasons: Seasons.SUMMER | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.35,
        depthMultiplier: 0.20,
        requiredLevel: 0,
        location: Location.MOUNTAIN_LAKE,
        baseValue: 200,
        baseEnergy: 25,
        baseHealing: 11
    },
    {
        id: 269,
        name: "Midnight Carp",
        difficulty: 55,
        motion: "mixed",
        minSize: 12,
        maxSize: 52,
        time: [2200, 2600],
        seasons: Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.33,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.MOUNTAIN_LAKE | Location.POND_FOREST | Location.GINGER_W_FRESH | Location.GINGER_NORTH,
        baseValue: 150,
        baseEnergy: 50,
        baseHealing: 22
    },
    {
        id: 836,
        name: "Stingray",
        difficulty: 80,
        motion: "sinker",
        minSize: 18,
        maxSize: 60,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 4,
        spawnMultiplier: 0.20,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.PIRATE_COVE,
        baseValue: 180,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 837,
        name: "Lionfish",
        difficulty: 50,
        motion: "smooth",
        minSize: 3,
        maxSize: 12,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.GINGER_SOUTH | Location.GINGER_SEAST | Location.GINGER_W_OCEAN,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 838,
        name: "Blue Discus",
        difficulty: 60,
        motion: "dart",
        minSize: 2,
        maxSize: 9,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 1,
        spawnMultiplier: 0.25,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.GINGER_W_FRESH | Location.GINGER_NORTH,
        baseValue: 120,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 156,
        name: "Ghostfish",
        difficulty: 50,
        motion: "mixed",
        minSize: 10,
        maxSize: 35,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.30,
        depthMultiplier: 0.30,
        requiredLevel: 0,
        location: Location.MINES_20 | Location.MINES_60,
        baseValue: 45,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 158,
        name: "Stonefish",
        difficulty: 65,
        motion: "sinker",
        minSize: 15,
        maxSize: 15,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.10,
        depthMultiplier: 0.10,
        requiredLevel: 3,
        location: Location.MINES_20,
        baseValue: 300,
        baseEnergy: 0,
        baseHealing: 0
    },
    {
        id: 159,
        name: "Crimsonfish",
        difficulty: 95,
        motion: "mixed",
        minSize: 20,
        maxSize: 20,
        time: [600, 2000],
        seasons: Seasons.SUMMER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 4,
        spawnMultiplier: 0.10,
        depthMultiplier: 0.10,
        requiredLevel: 5,
        location: Location.OCEAN_STARDEW,
        baseValue: 1500,
        baseEnergy: 38,
        baseHealing: 17,
        legendary: true
    },
    {
        id: 898,
        name: "Son of Crimsonfish",
        difficulty: 95,
        motion: "mixed",
        minSize: 20,
        maxSize: 20,
        time: [600, 2000],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 4,
        spawnMultiplier: 0.10,
        depthMultiplier: 0.10,
        requiredLevel: 5,
        location: Location.OCEAN_STARDEW,
        baseValue: 1500,
        baseEnergy: 38,
        baseHealing: 17,
        extendedFamily: true
    },
    {
        id: 160,
        name: "Angler",
        difficulty: 85,
        motion: "smooth",
        minSize: 18,
        maxSize: 18,
        time: [600, 2600],
        seasons: Seasons.FALL,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 4,
        spawnMultiplier: 0.05,
        depthMultiplier: 0.10,
        requiredLevel: 3,
        location: Location.RIVER_TOWN,
        baseValue: 900,
        baseEnergy: 25,
        baseHealing: 11,
        legendary: true
    },
    {
        id: 899,
        name: "Ms. Angler",
        difficulty: 85,
        motion: "smooth",
        minSize: 18,
        maxSize: 18,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 4,
        spawnMultiplier: 0.05,
        depthMultiplier: 0.10,
        requiredLevel: 3,
        location: Location.RIVER_TOWN,
        baseValue: 900,
        baseEnergy: 25,
        baseHealing: 11,
        extendedFamily: true
    },
    {
        id: 161,
        name: "Ice Pip",
        difficulty: 85,
        motion: "dart",
        minSize: 8,
        maxSize: 8,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.05,
        depthMultiplier: 0.10,
        requiredLevel: 5,
        location: Location.MINES_60,
        baseValue: 500,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 161,
        name: "Lava Eel",
        difficulty: 90,
        motion: "mixed",
        minSize: 32,
        maxSize: 32,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.05,
        depthMultiplier: 0.10,
        requiredLevel: 7,
        location: Location.MINES_100 | Location.VOLCANO,
        baseValue: 700,
        baseEnergy: 50,
        baseHealing: 22
    },
    {
        id: 163,
        name: "Legend",
        difficulty: 110,
        motion: "mixed",
        minSize: 50,
        maxSize: 50,
        time: [600, 2000],
        seasons: Seasons.SPRING,
        weather: Weather.RAINY,
        bestDepth: 5,
        spawnMultiplier: 0.00,
        depthMultiplier: 0.10,
        requiredLevel: 10,
        location: Location.MOUNTAIN_LAKE,
        baseValue: 5000,
        baseEnergy: 500,
        baseHealing: 225,
        legendary: true
    },
    {
        id: 900,
        name: "Legend II",
        difficulty: 110,
        motion: "mixed",
        minSize: 50,
        maxSize: 50,
        time: [600, 2000],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 5,
        spawnMultiplier: 0.00,
        depthMultiplier: 0.10,
        requiredLevel: 10,
        location: Location.MOUNTAIN_LAKE,
        baseValue: 5000,
        baseEnergy: 500,
        baseHealing: 225,
        extendedFamily: true
    },
    {
        id: 775,
        name: "Glacierfish",
        difficulty: 100,
        motion: "mixed",
        minSize: 27,
        maxSize: 27,
        time: [600, 2000],
        seasons: Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 5,
        spawnMultiplier: 0.00,
        depthMultiplier: 0.02,
        requiredLevel: 7,
        location: Location.POND_FOREST,
        baseValue: 1000,
        baseEnergy: 25,
        baseHealing: 11,
        legendary: true
    },
    {
        id: 902,
        name: "Glacierfish Jr.",
        difficulty: 100,
        motion: "mixed",
        minSize: 27,
        maxSize: 27,
        time: [600, 2000],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 5,
        spawnMultiplier: 0.00,
        depthMultiplier: 0.02,
        requiredLevel: 7,
        location: Location.POND_FOREST,
        baseValue: 1000,
        baseEnergy: 25,
        baseHealing: 11,
        extendedFamily: true
    },
    {
        id: 682,
        name: "Mutant Carp",
        difficulty: 80,
        motion: "dart",
        minSize: 36,
        maxSize: 36,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 5,
        spawnMultiplier: 0.00,
        depthMultiplier: 0.02,
        requiredLevel: 0,
        location: Location.SEWERS,
        baseValue: 1000,
        baseEnergy: 25,
        baseHealing: 11,
        legendary: true
    },
    {
        id: 901,
        name: "Radioactive Carp",
        difficulty: 80,
        motion: "dart",
        minSize: 36,
        maxSize: 36,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 5,
        spawnMultiplier: 0.00,
        depthMultiplier: 0.02,
        requiredLevel: 0,
        location: Location.SEWERS,
        baseValue: 1000,
        baseEnergy: 25,
        baseHealing: 11,
        extendedFamily: true
    },
    {
        id: 795,
        name: "Void Salmon",
        difficulty: 80,
        motion: "mixed",
        minSize: 24,
        maxSize: 65,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 2,
        spawnMultiplier: 0.33,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.SWAMP,
        baseValue: 150,
        baseEnergy: 63,
        baseHealing: 28
    },
    {
        id: 796,
        name: "Slimejack",
        difficulty: 55,
        motion: "dart",
        minSize: 8,
        maxSize: 25,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.BUG_LAIR,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 798,
        name: "Midnight Squid",
        difficulty: 55,
        motion: "sinker",
        minSize: 8,
        maxSize: 25,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.NIGHT_MARKET,
        baseValue: 100,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 799,
        name: "Spook Fish",
        difficulty: 60,
        motion: "dart",
        minSize: 8,
        maxSize: 25,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.NIGHT_MARKET,
        baseValue: 220,
        baseEnergy: 38,
        baseHealing: 17
    },
    {
        id: 800,
        name: "Blobfish",
        difficulty: 75,
        motion: "floater",
        minSize: 8,
        maxSize: 25,
        time: [600, 2600],
        seasons: Seasons.SPRING | Seasons.SUMMER | Seasons.FALL | Seasons.WINTER,
        weather: Weather.SUNNY | Weather.RAINY,
        bestDepth: 3,
        spawnMultiplier: 0.40,
        depthMultiplier: 0.10,
        requiredLevel: 0,
        location: Location.NIGHT_MARKET,
        baseValue: 500,
        baseEnergy: 38,
        baseHealing: 17
    },
];

export default Fish;